### ISSUE TITLE
Move from docker-engine to docker-ce

### ISSUE THREAD

**Issue by wingrunr21** [rockstor/rockstor-iso#21]
Docker engine was [announced to be succeeded by Docker CE](https://blog.docker.com/2017/06/announcing-docker-17-06-community-edition-ce/) in June. It'd be great to start thinking about upgrading the Rockstor docker requirement to match the new alignment. The 1.13.x are scheduled to be [EOL in February 2018](https://success.docker.com/Policies/Maintenance_Lifecycle) so moving over to CE before that would be great.

I haven't fully put it through its paces, but it looks like switching would be a matter of switching Rockstor's dependency from `docker-engine` to `docker-ce`, uninstalling existing versions, and upgrading. The Docker package repository would also need to be set up in the system.

[CentOS instructions](https://docs.docker.com/engine/installation/linux/docker-ce/centos/)

Sorry if this is the wrong repo for this issue. Only place I could find a reference to `docker-engine` itself is here.

**Comment by phillxnet** [comment]
@wingrunr21 Looks like this issue is now resolved by way of it's sister issue linked:
https://github.com/rockstor/rockstor-core/issues/1860
in the rockstor-core repo so I suggest this issue be closed as a duplicate of:
https://github.com/rockstor/rockstor-core/issues/1860
Thanks.

**Comment by wingrunr21** [comment]
Yep, agreed. Thanks!
