### ISSUE TITLE
remove sda requirement in ks.cfg

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-iso#7]
Perhaps revise ks.cfg over all.

http://forum.rockstor.com/t/installation-in-a-xen-vm/427/12

**Comment by holmesb** [comment]
Still can't install latest Rockstor (v3.8.9-02) as a XenServer VM because ks.cfg tells kickstart to ignore all disks except /dev/sda.  /dev/sda doesn't exist in XenServer VMs.

**Comment by schakrava** [comment]
This is no longer an issue as there is a easy workaround as documented by a user in this post: http://forum.rockstor.com/t/installation-in-a-xen-vm/427/20
